server:
  port: 8080
  servlet:
    context-path: /yuqiaopc

spring:
  datasource:
   



    #logging:
    #  level: DemoApplicationTests = trace
#    禁用模板缓存
  thymeleaf:
    cache: false
#  jpa:
mybatis:
  config-location: classpath:mybaties/mybatis-config.xml
  mapper-locations: classpath:mybaties/mapper/*.xml
#  打印sql
logging:
  level:
    com:
        mapper: INFO

#    show-sql: true
message:
  
